# Generated by Django 4.1.3 on 2022-12-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=3, null=True)),
                ('startCity', models.CharField(max_length=50, null=True)),
                ('Destination', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
